import { Navbar, NavbarLink, NavbarLogo, NavbarSpacer } from "@/components/ui";
import type { Metadata } from "next";
import { Geist, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const geist = Geist({
  variable: "--font-secondary",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-primary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Devroast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.variable} ${jetbrainsMono.variable} antialiased`}>
        <Navbar>
          <NavbarLogo />
          <NavbarSpacer />
          <NavbarLink href="#">leaderboard</NavbarLink>
        </Navbar>
        {children}
      </body>
    </html>
  );
}
